//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeptemberWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderItemID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string MenuItem { get; set; }
        public int TableNumber { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
