//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeptemberWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusHistory
    {
        public int StatusHistoryID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Status { get; set; }
        public Nullable<int> ChangedByUserID { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
