//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeptemberWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Smena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Smena()
        {
            this.UserSmena = new HashSet<UserSmena>();
        }
    
        public int SmenaID { get; set; }
        public System.DateTime SmenaDate { get; set; }
        public Nullable<int> WaiterID { get; set; }
        public Nullable<int> CookID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSmena> UserSmena { get; set; }
    }
}
